---
title: "ESSE2210_Project"
author: "Chethana Wickramasinghe"
date: "11/1/2020"
output: html_document
runtime: shiny
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(utils)
library(dplyr)
library(tidyverse)
library(scales)
library(openxlsx)

library(openair)
library(lubridate)

```



```{r echo=FALSE}

file <- file.choose()

air_samplying_data <- read.delim(file, header = FALSE)

names(air_samplying_data) <- paste0(air_samplying_data[1,], "_" , air_samplying_data[2,])# creating headers

air_samplying_data <- air_samplying_data[-c(1,2),] # remove the first to rows 

particles <- unique(air_samplying_data$`PM2.5_         Âµg/m3`)

ozone <- unique(air_samplying_data$O3_ppb)

benzene <- unique(air_samplying_data$Benzene_ppb)

nrow(air_samplying_data)
summary(air_samplying_data)

removed_text_data <- air_samplying_data

removed_text_data$O3_ppb <- as.numeric(removed_text_data$O3_ppb)
removed_text_data$Benzene_ppb<- as.numeric(removed_text_data$Benzene_ppb)
removed_text_data$`PM2.5_         Âµg/m3` <- as.numeric(removed_text_data$`PM2.5_         Âµg/m3`)
removed_text_data$Date_ <-dmy(removed_text_data$Date_)

# as.numeric(removed_text_data$O3_ppb, removed_text_data$Benzene_ppb, removed_text_data$`PM2.5_         Âµg/m3`)

removed_text_data <- removed_text_data %>% drop_na() %>% rename( PM = 'PM2.5_         Âµg/m3')

# removed_text_data <- air_samplying_data %>% mutate_at(c(3,5), as.numeric) %>% drop_na()

nrow(removed_text_data)

str(removed_text_data)

summary(removed_text_data)

# graphs

# hist(removed_text_data$`PM2.5_         Âµg/m3`)
# hist(removed_text_data$`O3_ppb`)
# hist(removed_text_data$`Benzene_ppb`)

# summaryPlot(mydata)

# ggplot(removed_text_data,  aes(Date_, O3_ppb)) + geom_point() +
#   theme(plot.caption = element_text(hjust = 0, size = 6),
#         plot.title = element_text(hjust = 0.5,size = 12, face = "bold"),
#         axis.title.x = element_text(hjust = 0.5, size = 15, face = "bold"),
#         axis.title.y = element_text(hjust = 0.5, size = 15, face = "bold"),
#         axis.text.x = element_text(hjust = 1, size = 10, angle = 45))

# ggplot(df, aes(x = month, y = avg)) + 
#   geom_bar(stat = "identity") + 
#   scale_x_date(NULL, date_labels = "%b %y", breaks = "month")

particle_data <- removed_text_data[1:3]
o3_data <- removed_text_data[c(1,2,4)] %>% drop_na()
benzene_data <- removed_text_data[c(1,2,5)]

```

```{r particledata}
# max recorded in 2019
top_highest_recorded_levels <- head(particle_data %>%arrange(desc(PM)), 8)
#   Date_      Time_    PM
#   <date>     <chr> <dbl>
# 1 2019-02-04 12:00    62
# 2 2019-12-20 22:00    59
# 3 2019-02-04 6:00     54
# 4 2019-12-20 21:00    54
# 5 2019-02-04 7:00     53
# 6 2019-02-04 8:00     53
# 7 2019-04-22 1:00     53
# 8 2019-02-06 10:00    52

unique(top_highest_recorded_levels$Date_)
# [1] "2019-02-04" "2019-12-20" "2019-04-22" "2019-02-06"

# months with highest recorded amount
unique(month(top_highest_recorded_levels$Date_))
# [1]  2 12  4

max(particle_data$PM)
# [1] 62 [µg/m3]

# Averaging Time: 24hour mean
mean((particle_data %>% group_by(day(Date_)) %>% summarise(meanpm = mean(PM)))$meanpm)
# [1] 8.285579

quantile(particle_data$PM, c(.32, .57, .98)) 
# 32% 57% 98% 
#   4   8  26

# Averaging Time: Annual mean
mean(particle_data$PM)
# [1] 8.279944


# scatter plot
ggplot(particle_data, aes( Date_,PM )) + geom_point(color= "#FF6666") +
  theme(plot.caption = element_text(hjust = 0, size = 6),
        plot.title = element_text(hjust = 0.5,size = 12, face = "bold"),
        axis.title.x = element_text(hjust = 0.5, size = 15, face = "bold"),
        axis.title.y = element_text(hjust = 0.5, size = 15, face = "bold"),
        axis.text.x = element_text(hjust = 1, size = 10, angle = 45))+
  labs(title = "Particulate Matter throughout 2019",
            x = "Month",
            y = "Particulate Matter [µg/m3]")


tmp <- particle_data %>% rename( PM = 'PM2.5_         Âµg/m3') %>% group_by(month = floor_date(Date_, unit = "month") ) %>%
 arrange(month = floor_date(Date_, unit = "month")) %>% summarise(sum = sum(PM), avg = mean(PM)) %>% replace(is.na(.), 0) %>%
 mutate(cs = cumsum(sum))

# cumsum
ggplot(tmp , aes(factor(month), cs)) + geom_bar(stat = "identity", fill = "#FF6666") +
  theme(plot.caption = element_text(hjust = 0, size = 6),
        plot.title = element_text(hjust = 0.5,size = 12, face = "bold"),
        axis.title.x = element_text(hjust = 0.5, size = 15, face = "bold"),
        axis.title.y = element_text(hjust = 0.5, size = 15, face = "bold"),
        axis.text.x = element_text(hjust = 1, size = 10, angle = 45)) +
  labs(title = "Monthly Cumulative Sum of Particulate Matter in 2019",
            x = "Month",
            y = "Cumulative Sum of Particulate Matter [µg/m3]") 

# mean
ggplot(tmp , aes(factor(month), avg)) + geom_bar(stat = "identity", fill = "#FF6666") +
  theme(plot.caption = element_text(hjust = 0, size = 6),
        plot.title = element_text(hjust = 0.5,size = 12, face = "bold"),
        axis.title.x = element_text(hjust = 0.5, size = 15, face = "bold"),
        axis.title.y = element_text(hjust = 0.5, size = 15, face = "bold"),
        axis.text.x = element_text(hjust = 1, size = 10, angle = 45))+
  labs(title = "Monthly Average amount of Particulate Matter in the air throughout 2019",
            x = "Month",
            y = "Average amount of Particulate Matterr [µg/m3]") 

tmp3 <- particle_data %>% rename( PM = 'PM2.5_         Âµg/m3') %>% mutate(Season = case_when(Season = month(Date_) == 3 | month(Date_) == 4 | month(Date_) == 5 ~ "Spring",
                                                                                              month(Date_) == 6 | month(Date_) == 7 | month(Date_) == 8 ~ "Summer",
                                                                                              month(Date_) == 9 | month(Date_) == 10 | month(Date_) == 11 ~ "Fall",
                                                                                             month(Date_) == 12 | month(Date_) == 1 | month(Date_) == 2 ~ "Winter"),
                                                                           ) %>% 
  group_by(Time_, Season) %>%
 arrange(Time_) %>% summarise(sum = sum(PM), avg = mean(PM)) %>% replace(is.na(.), 0) %>%
 mutate(cs = cumsum(sum)) %>%
  separate(Time_, c("Hours", "Minutes"), sep=":", remove = FALSE)


tmp3$Time <- as.POSIXct(tmp3$Time_, format="%H:%M")

ggplot(tmp3, aes(x=Time, y=avg, col=Season)) + 
  # geom_bar(stat = "identity",position = "dodge") #+
  geom_line(size=1)+
  labs(title = "Hourly Average Amount of Particulate Matter in the air throughout different Seasons in 2019",
            x = "Hours (24 hr format)",
            y = "Average amount of Particulate Matter [µg/m3]")+
  theme(plot.caption = element_text(hjust = 0, size = 6),
        plot.title = element_text(hjust = 0.5,size = 12, face = "bold"),
        axis.title.x = element_text(hjust = 0.5, size = 15, face = "bold"),
        axis.title.y = element_text(hjust = 0.5, size = 15, face = "bold"),
        axis.text.x = element_text(hjust = 1, size = 10, angle = 45))+
    scale_x_datetime(breaks = date_breaks("1 hour"), date_labels = "%H:%M")




```

```{r ozone}
# max recorded in 2019

top_highest_recorded_levels <- head(o3_data %>%arrange(desc(O3_ppb)), 8)
#        Date_ Time_ O3_ppb
# 1 2019-07-21 17:00     82
# 2 2019-07-21 16:00     80
# 3 2019-08-03 12:00     75
# 4 2019-08-03 13:00     75
# 5 2019-06-07 15:00     74
# 6 2019-07-22 16:00     74
# 7 2019-07-21 18:00     73
# 8 2019-08-03 11:00     73

unique(top_highest_recorded_levels$Date_)
# 1] "2019-07-21" "2019-08-03" "2019-06-07" "2019-07-22"

# months with highest recorded amount
unique(month(top_highest_recorded_levels$Date_))
# [1] 7 8 6

max(o3_data$O3_ppb)
# [1] 82 ppb

# Averaging Time: 24hour mean
mean((o3_data %>% group_by(day(Date_)) %>% summarise(meano3 = mean(O3_ppb)))$meano3)
# [1] 27.64747

quantile(o3_data$O3_ppb, c(.32, .57, .98)) 
# 32% 57% 98% 
#  22  30  58

# Averaging Time: Annual mean
mean(o3_data$O3_ppb)
# [1] 27.66188

# scatter plot
ggplot(o3_data, aes( Date_,O3_ppb )) + geom_point(color= "#09B8BD") +
  theme(plot.caption = element_text(hjust = 0, size = 6),
        plot.title = element_text(hjust = 0.5,size = 12, face = "bold"),
        axis.title.x = element_text(hjust = 0.5, size = 15, face = "bold"),
        axis.title.y = element_text(hjust = 0.5, size = 15, face = "bold"),
        axis.text.x = element_text(hjust = 1, size = 10, angle = 45))+
  labs(title = "Ozone throughout 2019",
            x = "Month",
            y = "Ozone [ppb]") 

tmp <- o3_data %>% group_by(month = floor_date(Date_, unit = "month") ) %>%
 arrange(month = floor_date(Date_, unit = "month"))%>% summarise(sum = sum(O3_ppb), avg = mean(O3_ppb)) %>%
 mutate(cs = cumsum(sum))

# cumsum
ggplot(tmp , aes(factor(month), cs)) + geom_bar(stat = "identity", fill= "#09B8BD") +
  theme(plot.caption = element_text(hjust = 0, size = 6),
        plot.title = element_text(hjust = 0.5,size = 12, face = "bold"),
        axis.title.x = element_text(hjust = 0.5, size = 15, face = "bold"),
        axis.title.y = element_text(hjust = 0.5, size = 15, face = "bold"),
        axis.text.x = element_text(hjust = 1, size = 10, angle = 45))+
  labs(title = "Monthly Cumulative Sum of Ozone in 2019",
            x = "Month",
            y = "Cumulative Sum of Ozone [ppb]") 

# mean
ggplot(tmp , aes(factor(month), avg)) + geom_bar(stat = "identity", fill= "#09B8BD") +
  theme(plot.caption = element_text(hjust = 0, size = 6),
        plot.title = element_text(hjust = 0.5,size = 12, face = "bold"),
        axis.title.x = element_text(hjust = 0.5, size = 15, face = "bold"),
        axis.title.y = element_text(hjust = 0.5, size = 15, face = "bold"),
        axis.text.x = element_text(hjust = 1, size = 10, angle = 45))+
  labs(title = "Monthly Average amount of Ozone in the air throughout 2019",
            x = "Month",
            y = "Average amount of Ozone [ppb]") 


tmp3 <- o3_data %>% mutate(Season = case_when(Season = month(Date_) == 3 | month(Date_) == 4 | month(Date_) == 5 ~ "Spring",
                                                                                              month(Date_) == 6 | month(Date_) == 7 | month(Date_) == 8 ~ "Summer",
                                                                                              month(Date_) == 9 | month(Date_) == 10 | month(Date_) == 11 ~ "Fall",
                                                                                             month(Date_) == 12 | month(Date_) == 1 | month(Date_) == 2 ~ "Winter"),
                                                                           ) %>% 
  group_by(Time_, Season) %>%
 arrange(Time_) %>% summarise(sum = sum(O3_ppb), avg = mean(O3_ppb)) %>% replace(is.na(.), 0) %>%
 mutate(cs = cumsum(sum)) %>%
  separate(Time_, c("Hours", "Minutes"), sep=":", remove = FALSE)

tmp3$Time <- as.POSIXct(tmp3$Time_, format="%H:%M")

ggplot(tmp3, aes(x=Time, y=avg, col=Season)) + 
  # geom_bar(stat = "identity",position = "dodge") #+
  geom_line(size=1)+
  labs(title = "Hourly Average Amount of Ozone in the air throughout different Seasons in 2019",
            x = "Hours (24 hr format)",
            y = "Average amount of Ozone [ppb]")+
  theme(plot.caption = element_text(hjust = 0, size = 6),
        plot.title = element_text(hjust = 0.5,size = 12, face = "bold"),
        axis.title.x = element_text(hjust = 0.5, size = 15, face = "bold"),
        axis.title.y = element_text(hjust = 0.5, size = 15, face = "bold"),
        axis.text.x = element_text(hjust = 1, size = 10, angle = 45))+
    scale_x_datetime(breaks = date_breaks("1 hour"), date_labels = "%H:%M")

```

```{r benzene}

# max recorded in 2019
top_highest_recorded_levels <- head(benzene_data %>%arrange(desc(Benzene_ppb)), 8)
#        Date_ Time_ Benzene_ppb
# 1 2019-01-12  1:00       18.24
# 2 2019-01-24  1:00       16.11
# 3 2019-12-20  3:00       15.50
# 4 2019-02-10  2:00       15.46
# 5 2019-02-10  1:00       13.83
# 6 2019-02-19 10:00       13.77
# 7 2019-01-12  8:00       13.00
# 8 2019-01-09  5:00       12.65

unique(top_highest_recorded_levels$Date_)
# [1] "2019-01-12" "2019-01-24" "2019-12-20" "2019-02-10" "2019-02-19" "2019-01-09"

# months with highest recorded amount
unique(month(top_highest_recorded_levels$Date_))
# [1]  1 12  2

max(benzene_data$Benzene_ppb)
# [1] 18.24 ppb

# Averaging Time: 24hour mean
mean((benzene_data %>% group_by(day(Date_)) %>% summarise(meanbenzene = mean(Benzene_ppb)))$meanbenzene)
# [1] 0.2130141

quantile(benzene_data$Benzene_ppb, c(.32, .57, .98)) 
#    32%    57%    98% 
# 0.0000 0.0000 2.3256

# Averaging Time: Annual mean
mean(benzene_data$Benzene_ppb)
# [1] 0.2131907

# scatter plot
ggplot(benzene_data, aes( Date_,Benzene_ppb )) + geom_point(color= "#B69233") +
  theme(plot.caption = element_text(hjust = 0, size = 6),
        plot.title = element_text(hjust = 0.5,size = 12, face = "bold"),
        axis.title.x = element_text(hjust = 0.5, size = 15, face = "bold"),
        axis.title.y = element_text(hjust = 0.5, size = 15, face = "bold"),
        axis.text.x = element_text(hjust = 1, size = 10, angle = 45))+
  labs(title = "Benzene throughout 2019",
            x = "Month",
            y = "Benzene [ppb]")

tmp <- benzene_data %>% drop_na() %>% group_by(month = floor_date(Date_, unit = "month") ) %>%
 arrange(month = floor_date(Date_, unit = "month"))%>% summarise(sum = sum(Benzene_ppb), avg = mean(Benzene_ppb)) %>%  replace(is.na(.), 0) %>%
 mutate(cs = cumsum(sum))

# cumsum
ggplot(tmp , aes(factor(month), cs)) + geom_bar(stat = "identity", fill= "#B69233") +
  theme(plot.caption = element_text(hjust = 0, size = 6),
        plot.title = element_text(hjust = 0.5,size = 12, face = "bold"),
        axis.title.x = element_text(hjust = 0.5, size = 15, face = "bold"),
        axis.title.y = element_text(hjust = 0.5, size = 15, face = "bold"),
        axis.text.x = element_text(hjust = 1, size = 10, angle = 45))+
  labs(title = "Monthly Cumulative Sum of Benzene in 2019",
            x = "Month",
            y = "Cumulative Sum of Benzene [ppb]") 

# mean
ggplot(tmp , aes(factor(month), avg)) + geom_bar(stat = "identity", fill= "#B69233") +
  theme(plot.caption = element_text(hjust = 0, size = 6),
        plot.title = element_text(hjust = 0.5,size = 12, face = "bold"),
        axis.title.x = element_text(hjust = 0.5, size = 15, face = "bold"),
        axis.title.y = element_text(hjust = 0.5, size = 15, face = "bold"),
        axis.text.x = element_text(hjust = 1, size = 10, angle = 45))+
  labs(title = "Monthly Average amount of Benzene in the air throughout 2019",
            x = "Month",
            y = "Average amount of Benzene [ppb]") 


tmp3 <- benzene_data %>% mutate(Season = case_when(Season = month(Date_) == 3 | month(Date_) == 4 | month(Date_) == 5 ~ "Spring",
                                                                                              month(Date_) == 6 | month(Date_) == 7 | month(Date_) == 8 ~ "Summer",
                                                                                              month(Date_) == 9 | month(Date_) == 10 | month(Date_) == 11 ~ "Fall",
                                                                                             month(Date_) == 12 | month(Date_) == 1 | month(Date_) == 2 ~ "Winter"),
                                                                           ) %>% 
  group_by(Time_, Season) %>%
 arrange(Time_) %>% summarise(sum = sum(Benzene_ppb), avg = mean(Benzene_ppb)) %>% replace(is.na(.), 0) %>%
 mutate(cs = cumsum(sum)) %>%
  separate(Time_, c("Hours", "Minutes"), sep=":", remove = FALSE)

tmp3$Time <- as.POSIXct(tmp3$Time_, format="%H:%M")

ggplot(tmp3, aes(x=Time, y=avg, col=Season)) + 
  # geom_bar(stat = "identity",position = "dodge") #+
  geom_line(size=1)+
  labs(title = "Hourly Average Amount of Benzene in the air throughout different Seasons in 2019",
            x = "Hours (24 hr format)",
            y = "Average amount of Benzene [ppb]")+
  theme(plot.caption = element_text(hjust = 0, size = 6),
        plot.title = element_text(hjust = 0.5,size = 12, face = "bold"),
        axis.title.x = element_text(hjust = 0.5, size = 15, face = "bold"),
        axis.title.y = element_text(hjust = 0.5, size = 15, face = "bold"),
        axis.text.x = element_text(hjust = 1, size = 10, angle = 45))+
    scale_x_datetime(breaks = date_breaks("1 hour"), date_labels = "%H:%M")



```

```{r all}

removed_text_data <- as_tibble(removed_text_data) %>% drop_na()
tmp <- removed_text_data %>% rename( PM = 'PM2.5_         Âµg/m3') %>% group_by(month = floor_date(Date_, unit = "month") ) %>%
 arrange(month = floor_date(Date_, unit = "month")) %>% summarise(PM_sum = sum(PM), PM_avg = mean(PM), O3_sum = sum(O3_ppb), O3_avg = mean(O3_ppb), Ben_sum = sum(Benzene_ppb), Ben_avg = mean(Benzene_ppb)) %>% replace(is.na(.), 0) %>%
 mutate(PM_cs = cumsum(PM_sum), O3_cs = cumsum(O3_sum), Ben_cs = cumsum(Ben_sum))

tmp_long_avg <- pivot_longer(tmp, cols = ends_with("avg"), names_to = "AVG", values_to = "AVG_Value") %>% select(month, AVG, AVG_Value)


ggplot(tmp_long_avg , aes(x=factor(month) , y= AVG_Value)) + geom_bar(stat = "identity",position = "dodge") +
    facet_wrap(~AVG, ncol=1, as.table = TRUE, scale = "free") +
  theme(plot.caption = element_text(hjust = 0, size = 6),
        plot.title = element_text(hjust = 0.5,size = 12, face = "bold"),
        axis.title.x = element_text(hjust = 0.5, size = 15, face = "bold"),
        axis.title.y = element_text(hjust = 0.5, size = 15, face = "bold"),
        axis.text.x = element_text(hjust = 1, size = 10, angle = 45))

tmp_long_cumsum <- pivot_longer(tmp, cols = ends_with("cs"), names_to = "CUMSUM", values_to = "CUMSUM_Value") %>% select(month, CUMSUM, CUMSUM_Value)

ggplot(tmp_long_cumsum , aes(x=factor(month) , y= CUMSUM_Value)) + geom_bar(stat = "identity",position = "dodge") +
    facet_wrap(~CUMSUM, ncol=1, as.table = TRUE, scale = "free") +
  theme(plot.caption = element_text(hjust = 0, size = 6),
        plot.title = element_text(hjust = 0.5,size = 12, face = "bold"),
        axis.title.x = element_text(hjust = 0.5, size = 15, face = "bold"),
        axis.title.y = element_text(hjust = 0.5, size = 15, face = "bold"),
        axis.text.x = element_text(hjust = 1, size = 10, angle = 45))


max(removed_text_data$`PM2.5_         Âµg/m3`)
# [1] 62
max(removed_text_data$O3_ppb)
# [1] 82
max(removed_text_data$Benzene_ppb)
# [1] 18.24
mean(removed_text_data$Benzene_ppb)

min(removed_text_data$Benzene_ppb)

x <- data.frame("SN" = 1:2, "Age" = c(21,15), "Name" = c("John","Dora"))

summarydata = data.frame("Pollutant" = c("Particla Matter [µg/m3]", "Ozone [ppb]", "Benzene [ppb]"),
                             "Maximum Amount Recorded" = c( max(removed_text_data$`PM2.5_         Âµg/m3`), max(removed_text_data$O3_ppb) , max(removed_text_data$Benzene_ppb) ))
                         # ,"Minimum Amount Recourded" = c( min(removed_text_data$`PM2.5_         Âµg/m3`), min(removed_text_data$O3_ppb) , min(removed_text_data$Benzene_ppb)) )


renderTable({
  
  summarydata
  
})

ggplot(removed_text_data, aes(PM, O3_ppb )) + geom_point()

library(corrplot)

corrplot(cor(removed_text_data[3:5]),
  method = "number",
  type = "upper" # show only upper side
)

datacor <- cor(removed_text_data[3:5])

corrplot(datacor, type = "upper", order = "hclust", 
         tl.col = "black", tl.srt = 45)

```





